from django.db import models

# Create your models here.
class AutoLog(models.Model):
    log = models.CharField(max_length=200)
    date = models.DateTimeField()
    
class Properti(models.Model):
    judul = models.CharField(max_length=255, null=True, blank=True)
    harga = models.CharField(max_length=100, null=True, blank=True)
    cicilan = models.CharField(max_length=100, null=True, blank=True)
    kecamatan = models.CharField(max_length=255, null=True, blank=True)
    luas_tanah = models.CharField(max_length=100, null=True, blank=True)
    luas_bangunan = models.CharField(max_length=100, null=True, blank=True)
    link = models.URLField(max_length=500, null=True, blank=True)
    fasilitas = models.TextField(null=True, blank=True)
    last_update = models.CharField(max_length=100, null=True, blank=True)
    kamar_tidur = models.FloatField(null=True, blank=True)
    kamar_mandi = models.FloatField(null=True, blank=True)
    luas_tanah_dupe = models.CharField(max_length=100, null=True, blank=True)
    luas_bangunan_dupe = models.CharField(max_length=100, null=True, blank=True)
    carport = models.FloatField(null=True, blank=True)
    tipe_properti = models.CharField(max_length=255, null=True, blank=True)
    sertifikat = models.CharField(max_length=100, null=True, blank=True)
    daya_listrik = models.CharField(max_length=100, null=True, blank=True)
    kamar_pembantu = models.FloatField(null=True, blank=True)
    kamar_mandi_pembantu = models.FloatField(null=True, blank=True)
    ruang_makan = models.CharField(max_length=255, null=True, blank=True)
    ruang_tamu = models.CharField(max_length=255, null=True, blank=True)
    kondisi_perabotan = models.CharField(max_length=255, null=True, blank=True)
    material_bangunan = models.CharField(max_length=255, null=True, blank=True)
    material_lantai = models.CharField(max_length=255, null=True, blank=True)
    garasi = models.FloatField(null=True, blank=True)
    jumlah_lantai = models.FloatField(null=True, blank=True)
    hadap = models.CharField(max_length=100, null=True, blank=True)
    konsep_dan_gaya_rumah = models.CharField(max_length=255, null=True, blank=True)
    pemandangan = models.CharField(max_length=255, null=True, blank=True)
    terjangkau_internet = models.CharField(max_length=255, null=True, blank=True)
    lebar_jalan = models.CharField(max_length=100, null=True, blank=True)
    tahun_dibangun = models.FloatField(null=True, blank=True)
    tahun_di_renovasi = models.FloatField(null=True, blank=True)
    sumber_air = models.CharField(max_length=100, null=True, blank=True)
    hook = models.CharField(max_length=100, null=True, blank=True)
    kondisi_properti = models.CharField(max_length=255, null=True, blank=True)
    tipe_iklan = models.CharField(max_length=100, null=True, blank=True)
    id_iklan = models.CharField(max_length=100, null=True, blank=True)
    deskripsi = models.TextField(null=True, blank=True)
    dapur = models.FloatField(null=True, blank=True)