# Generated by Django 5.0.6 on 2024-06-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_properti"),
        ("users", "0002_userinput"),
    ]

    operations = []
