# Generated by Django 5.0.6 on 2024-06-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_training_ac_alter_training_akses_parkir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRegresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateField()),
                ('versi', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='LabelEncoder',
        ),
    ]
